org.gradle.jvmargs=-Xmx2048M

#minecraft
minecraft_version=1.21
enabled_platforms=fabric,neoforge

#mod
archives_base_name=mcdar
mod_version=1.4.0
maven_group=dev.timefall

#loaders
fabric_api_version=0.102.0+1.21
fabric_loader_version=0.16.2

neoforge_version=21.0.167

#yarn version
yarn_mappings=9

#dependencies
fzzyConfigVersion=0.7.0+1.21
mcdxVersion=0.1.1+mc1.21