package chronosacaria.mcdar.enums;

public enum DefenciveArtefactID {
    ENCHANTERS_TOME,
    IRON_HIDE_AMULET,
    POWERSHAKER,
    //SATCHEL_OF_ELIXIRS,
    //SATCHEL_OF_SNACKS,
    SOUL_HEALER,
    TOTEM_OF_REGENERATION,
    TOTEM_OF_SHIELDING,
    TOTEM_OF_SOUL_PROTECTION,
    WIND_HORN
}
